### PR TITLE
v1.8.1 supporting factorio 1.1.1

### PR DESCRIPTION
**Pull request by voidus**
I started a game, placed some steam engines and everything seems to work. I'm not sure if there are any more tests I can/should run.

### CODE REVIEW

**Comment by MrTyton** [comment]
+1

**Comment by Zomis** [comment]
The other versions have been 1.x.0, maybe this should be too?

I should maybe have looked for other pull requests before I created my own :D

**Comment by voidus** [comment]
I don't know about 1.1.0, I feel it suggests that the mod only works with that specific patch version? 1.1 works though.

**Comment by Zomis** [comment]
> I don't know about 1.1.0, I feel it suggests that the mod only works with that specific patch version? 1.1 works though.

@voidus I mean that this mod has been doing a 1.x.0 release whenever a new version of Factorio is out, so I'm guessing the author might want a 1.9.0 instead of 1.8.1.

But yes, I have also verified that this mod work just fine with both Factorio 1.0 and 1.1.

**Comment by voidus** [comment]
Ah, yeah, I misunderstood that. @Suprcheese if you want the bump, let me know and I'll update it :)

**Comment by Suprcheese** [comment]
Back from vacation, thanks everyone for checking that it still works with the current version. I'll push the update out shortly.

**Pull request merged**
